spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/odontotal}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

aws.access.key.id=${AWS_ACCESS_KEY_ID:dummy}
aws.secret.access.key=${AWS_SECRET_ACCESS_KEY:dummy}
aws.region=${AWS_REGION:us-east-1}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:email}
spring.mail.password=${MAIL_PASSWORD:password-email}
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

frontend.url=${FRONTEND_URL:http://localhost:5173/}